BUGS-NYU/nyu-cs-wiki

- .github/workflows/deploy.yml
- .github/workflows/test-deploy.yml
- docs/All/classes.md
- docs/All/intro.md
- docs/All/schedule.md
- docs/CAS/intro.md
- docs/Tandon/huss.md
- docs/Tandon/intro.md
- docs/Tandon/software_engineering.md
- docusaurus.config.js
- package-lock.json
> Add initial pages and deployment

- docusaurus.config.js
- src/css/custom.css
- src/pages/index.js
- src/pages/index.module.css
> Update Homepage and Colors

- docs/All/research.md
> Fix typo in docs

- docs/All/fellowships.md
There were some fellowships in the old wiki, that could be good to add here.
> add fellowships from old wiki

- docs/Academics/classes.md
- package-lock.json
> [Documentation Contribution] Added Intro to Offensive Security and fixed typo

- .github/workflows/deploy.yml
- .github/workflows/test-deploy.yml
- README.md
- docusaurus.config.js
- package-lock.json
- package.json
Switch to an open source search solution - [Lunr](https://github.com/praveenn77/docusaurus-lunr-search). I tried a few options, this seems to be the most responsive, most easily customizable, and best looking. It is also anecdotally more responsive than algolia because it does not make network requests. 
If there is a need to switch to the new algolia UI, I believe that is also possible (however I kind of like this UI more).
Addresses #64
> Move from Algolia to Lunr search

- docs/Opportunities/VIP/hsrn.md
basically what the title says.
(change: just squash all commits together)
> Add a description of the HSRN VIP

- docs/Opportunities/Internships/internships.md
I fixed the typo "interships". Also added some stuff to the description.
> Fixed the Internships page typo

- docs/Opportunities/Fellowships/fellowships.md
Basically just the title.
Add the rabbitholeathon retreat.
https://www.rabbitholeathon.com/
> add rabbitholeathon

- docs/Recreation/chipotle.md
I lived at Broome last year so yeah
> Add Spring St Chipotle

- docs/Opportunities/Hackathons/hackNYU.md
- docs/Opportunities/Hackathons/hackathons.md
- docs/Opportunities/opportunities.md
Added details on Hackathon and HackNYU
PR for #82
> Hackathon and HackNYU 

- docs/Social/free.md
#9 #24
Potentially add a discount section for stuff that is not free
> ADD free stuff

- docs/Opportunities/Hackathons/hackNYU.md
> add more information to hackNYU

- docs/Opportunities/opportunities.md
> Add Links to Opportunities Diagram

- CONTRIBUTING
- README.md
Added a few style/legal guidelines; let me know if there's anything else worth adding.
> Create Contribution Guidelines

- docs/Opportunities/resume.md
> Add resume page

- docs/Recreation/discounts.md
> add discounts page

- docs/Opportunities/Internal/TA.md
> Add TA/Tutor Page

- docs/Opportunities/Internships/internships.md
This briefly touches on all of the following: various types of interviews, practice methods, reaching out to recruiters, more detailed resume advice, and other resources. I wrote this post to help some people out and have been giving it to people who've asked me, but I think it could be really useful for more NYU students to have so I'm making a PR to add this to the wiki.
> Added detailed guide on the internship process to resources

- docs/Recreation/housing.md
Co-authored-by: aminoa 28660350+aminoa@users.noreply.github.com
Co-authored-by: rilieo rilesdou@gmail.com
Co-authored-by: ejz123 ejz5271@nyu.edu
> Add housing page

- docs/Opportunities/Internal/clubs.md
- Changed `Poly Programming Team` to `Poly Programming Club`
- Added Engage and Instagram links
> Update Poly Programming Club Information

- docs/Recreation/game_center.md
I updated the website of NYU game center and add some info about the library and playtest Thursday.
> Update about the NYU Game Center page

- docs/Academics/classes.md
Hey all, his PR adds AIT to the list of CAS classes in classes.md
> doc: added AIT to list of classes
